sudo: required
services: 
    - docker

before_install:
    - docker build -t zevocorp/zevo -f Dockerfile.dev .

script:
    - docker run -e CI=true zevocorp/zevo npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "zevo"
    env: "Zevo-env-1"
    bucket_name: "elasticbeanstalk-ap-south-1-032348315066"
    bucket_path: "zevo"
    label: "zevo"
    on:
        branch: master
    access_key_id: 
        secure: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY