sudo: required
services: 
    - docker

before_install:
    - docker build -t zevocorp/zevo -f Dockerfile.dev .

script:
    - docker run -e CI=true zevocorp/zevo npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "zevo"
    env: "Zevo-env"
    bucket_name: "elasticbeanstalk-ap-south-1-032348315066"
    on:
        branch: master
    access_key_id: "AKIAQPCA4DW5PANVEYNP"
    secret_access_key: "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"