sudo: required
services: 
    - docker

before_install:
    - docker build -t zevocorp/zevo -f Dockerfile.dev .

script:
    - docker run -e CI=true zevocorp/zevo npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "web"
    env: "Web-env"
    bucket_name: "elasticbeanstalk-ap-south-1-032348315066"
    bucket_path: "web"
    label: "Sample Application"
    on:
        branch: master
    access_key_id : ID
    secret_access_key: 
        secure: KEY